"""WAF and CDN detection analysis.

Detection patterns adapted from wafw00f (BSD-3-Clause):
https://github.com/EnableSecurity/wafw00f
"""

import re
from typing import Any, Dict, List, Optional, Set, Tuple

# Higher value wins when multiple vendors match (reduces edge false positives).
DETECTION_PRIORITY: Dict[str, int] = {
    "cloudflare": 100,
    "akamai": 95,
    "fastly": 90,
    "cloudfront": 90,
    "google": 88,
    "azure-front-door": 85,
    "imperva-incapsula": 85,
    "sucuri": 80,
    "aws-elb": 75,
    "citrix-netscaler": 70,
    "barracuda": 65,
    "fortinet": 65,
    "modsecurity": 60,
    "checkpoint": 50,
    "f5-big-ip": 40,
    "sectigo": 30,
}

MANUFACTURERS: Dict[str, str] = {
    "cloudflare": "Cloudflare Inc.",
    "akamai": "Akamai Technologies",
    "fastly": "Fastly",
    "cloudfront": "Amazon",
    "google": "Google",
    "azure-front-door": "Microsoft",
    "imperva-incapsula": "Imperva Inc.",
    "sucuri": "Sucuri Inc.",
    "aws-elb": "Amazon",
    "citrix-netscaler": "Citrix Systems",
    "barracuda": "Barracuda Networks",
    "fortinet": "Fortinet",
    "modsecurity": "SpiderLabs",
    "checkpoint": "Check Point",
    "f5-big-ip": "F5 Networks",
    "sectigo": "Sectigo",
}

# (header_name, value_regex) — header names compared case-insensitively.
HeaderPattern = Tuple[str, str]
CookiePattern = str
BodyPattern = str


class WAFCDNDetector:
    """Detector for WAF and CDN services."""

    EDGE_INDICATORS = [
        "via",
        "x-cache",
        "x-served-by",
        "x-cache-hits",
        "age",
        "server-timing",
        "alt-svc",
        "x-edge-location",
    ]

    # wafw00f-inspired signatures plus legacy substring markers.
    SIGNATURES: Dict[str, Dict[str, Any]] = {
        "cloudflare": {
            "headers": [
                ("server", r"cloudflare"),
                ("server", r"cloudflare[-_]nginx"),
                ("cf-ray", r".+"),
                ("cf-cache-status", r".+"),
            ],
            "cookies": [r"__cfduid", r"__cf_bm"],
            "body": [],
            "substrings": ["cf-ray", "server: cloudflare"],
        },
        "akamai": {
            "headers": [
                ("server", r"AkamaiGHost"),
                ("x-akamai-transformed", r".+"),
                ("x-akamai-request-id", r".+"),
            ],
            "cookies": [],
            "body": [],
            "substrings": ["akamai", "x-akamai", "akamai-edgesuite", "akamai-grn"],
        },
        "fastly": {
            "headers": [
                ("x-fastly-request-id", r"\w+"),
                ("x-served-by", r"^cache-[a-z]{3}\d+-[A-Z]{3}"),
                ("x-timer", r".+"),
            ],
            "cookies": [],
            "body": [],
            "substrings": ["fastly", "x-cache-hits"],
        },
        "cloudfront": {
            "headers": [
                ("server", r"Cloudfront"),
                ("via", r"([0-9\.]+?)? \w+?\.cloudfront\.net \(Cloudfront\)"),
                ("x-amz-cf-id", r".+"),
                ("x-amz-cf-pop", r".+"),
                ("x-cache", r"Error from Cloudfront"),
            ],
            "cookies": [],
            "body": [r"Generated by cloudfront \(CloudFront\)"],
            "substrings": ["cloudfront", "via: 1.1 cloudfront"],
        },
        "azure-front-door": {
            "headers": [
                ("x-azure-ref", r".+"),
                ("x-azure-fdid", r".+"),
            ],
            "cookies": [],
            "body": [],
            "substrings": ["x-azure-ref", "x-azure-fdid", "azurefd"],
        },
        "imperva-incapsula": {
            "headers": [],
            "cookies": [r"^incap_ses.*?=", r"^visid_incap.*?="],
            "body": [
                r"incapsula incident id",
                r"powered by incapsula",
                r"/_Incapsula_Resource",
            ],
            "substrings": ["incap_ses", "visid_incap", "incapsula"],
        },
        "f5-big-ip": {
            "headers": [
                ("x-cnection", r"close"),
                ("x-waf", r".+"),
                ("x-apm-session", r".+"),
            ],
            "cookies": [r"^bigipserver", r"^TS[a-fA-F0-9]{8}=.+", r"^TS[a-fA-F0-9]{6}=.+"],
            "body": [
                r"the requested url was rejected",
                r"please consult with your administrator",
            ],
            "substrings": ["bigip", "server: f5"],
            "body_all": [
                [r"the requested url was rejected", r"please consult with your administrator"],
            ],
        },
        "citrix-netscaler": {
            "headers": [
                ("via", r"NS\-CACHE"),
                ("cneonction", r"^(keep alive|close)"),
                ("nnCoection", r"^(keep alive|close)"),
            ],
            "cookies": [r"^(ns_af=|citrix_ns_id|NSC_)"],
            "body": [
                r"(NS Transaction|AppFW Session) id",
                r"Violation Category.{0,5}?APPFW_",
                r"Citrix\|NetScaler",
            ],
            "substrings": ["citrix", "netscaler", "ns-cookiemodule"],
        },
        "aws-elb": {
            "headers": [
                ("x-amz-id", r".+"),
                ("x-amz-request-id", r".+"),
                ("server", r"aws.?elb"),
                ("x-amzn-trace-id", r".+"),
                ("x-blocked-by-waf", r"Blocked_by_custom_response_for_AWSManagedRules.*"),
            ],
            "cookies": [r"^aws.?alb="],
            "body": [],
            "substrings": ["awselb", "server: awselb"],
        },
        "sucuri": {
            "headers": [
                ("x-sucuri-id", r".+"),
                ("x-sucuri-cache", r".+"),
                ("server", r"Sucuri(\-Cloudproxy)?"),
                ("x-sucuri-block", r".+"),
            ],
            "cookies": [],
            "body": [
                r"Access Denied.{0,6}?Sucuri Website Firewall",
                r"<title>Sucuri WebSite Firewall.{0,6}?(CloudProxy)?.{0,6}?Access Denied",
                r"sucuri\.net/privacy\-policy",
                r"cdn\.sucuri\.net/sucuri[-_]firewall[-_]block\.css",
                r"cloudproxy@sucuri\.net",
            ],
            "substrings": ["sucuri", "x-sucuri"],
        },
        "barracuda": {
            "headers": [],
            "cookies": [
                r"^barra_counter_session=",
                r"^BNI__BARRACUDA_LB_COOKIE=",
                r"^BNI_persistence=",
                r"^BN[IE]S_.*?=",
            ],
            "body": [r"Barracuda\.Networks"],
            "substrings": ["barracuda", "barra"],
        },
        "fortinet": {
            "headers": [],
            "cookies": [r"^FORTIWAFSID="],
            "body": [r"\.fgd_icon", r"web\.page\.blocked"],
            "substrings": ["fortinet", "fortiweb"],
            "body_all": [
                [
                    r"fgd_icon",
                    r"web\.page\.blocked",
                    r"url",
                    r"attack\.id",
                    r"message\.id",
                    r"client\.ip",
                ],
            ],
        },
        "modsecurity": {
            "headers": [("server", r"(mod_security|Mod_Security|NOYB)")],
            "cookies": [],
            "body": [
                r"This error was generated by Mod.?Security",
                r"rules of the mod.security.module",
                r"mod.security.rules triggered",
                r"Protected by Mod.?Security",
                r"/modsecurity[\-_]errorpage/",
                r"modsecurity iis",
            ],
            "substrings": [],
            "status_reason": [(403, r"ModSecurity Action"), (406, r"ModSecurity Action")],
        },
        "google": {
            "headers": [
                ("server", r"esf"),
                ("server", r"google frontend"),
                ("server", r"gws"),
                ("via", r"1\.1 google"),
                ("x-cloud-trace-context", r".+"),
                ("x-guploader-uploadid", r".+"),
                ("x-goog-generation", r".+"),
                ("x-goog-hash", r".+"),
            ],
            "cookies": [],
            "body": [],
            "substrings": ["via: 1.1 google"],
        },
        "checkpoint": {
            "headers": [("x-checkpoint", r".+")],
            "cookies": [],
            "body": [],
            "substrings": ["checkpoint"],
        },
        "sectigo": {
            "headers": [("x-sectigo", r".+")],
            "cookies": [],
            "body": [],
            "substrings": ["sectigo"],
        },
    }

    def detect(
        self,
        headers: Dict[str, List[str]],
        body: Optional[str] = None,
        status_code: Optional[int] = None,
        title: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Detect WAF/CDN services from HTTP headers and optional body content."""
        header_blob = self._flatten_headers(headers)
        content_blob = self._build_content_blob(body, title)
        cookie_names = self._extract_cookie_names(headers)

        detected_evidence: Dict[str, List[str]] = {}

        for vendor, signature in self.SIGNATURES.items():
            vendor_evidence = self._match_vendor(
                signature,
                headers,
                header_blob,
                cookie_names,
                content_blob,
                status_code,
            )
            if vendor_evidence:
                detected_evidence[vendor] = vendor_evidence

        primary_service = self._select_primary(detected_evidence)
        services = self._filter_noise(detected_evidence, primary_service)

        edge_headers = []
        for edge_indicator in self.EDGE_INDICATORS:
            if edge_indicator.lower() in header_blob:
                edge_headers.append(edge_indicator)

        return {
            "services": sorted(services),
            "primary_service": primary_service,
            "manufacturer": MANUFACTURERS.get(primary_service) if primary_service else None,
            "evidence": {k: detected_evidence[k] for k in services if k in detected_evidence},
            "edge_indicators": edge_headers,
            "has_waf_cdn": len(services) > 0,
            "has_edge_caching": len(edge_headers) > 0,
        }

    def _match_vendor(
        self,
        signature: Dict[str, Any],
        headers: Dict[str, List[str]],
        header_blob: str,
        cookie_names: List[str],
        content_blob: str,
        status_code: Optional[int],
    ) -> List[str]:
        evidence: List[str] = []

        for header_name, pattern in signature.get("headers", []):
            match = self._match_header(headers, header_name, pattern)
            if match:
                evidence.append(f"header:{header_name}={match}")

        for pattern in signature.get("cookies", []):
            for cookie_name in cookie_names:
                if re.search(pattern, cookie_name, re.IGNORECASE):
                    evidence.append(f"cookie:{cookie_name}")
                    break

        for pattern in signature.get("body", []):
            if content_blob and re.search(pattern, content_blob, re.IGNORECASE):
                evidence.append(f"body:{pattern}")

        for patterns in signature.get("body_all", []):
            if content_blob and all(
                re.search(p, content_blob, re.IGNORECASE) for p in patterns
            ):
                evidence.append(f"body_all:{','.join(patterns[:2])}")

        for substring in signature.get("substrings", []):
            if substring.lower() in header_blob:
                evidence.append(f"substring:{substring}")

        for expected_status, reason_pattern in signature.get("status_reason", []):
            if status_code == expected_status:
                reason = self._get_header_value(headers, "reason")
                if reason and re.search(reason_pattern, reason, re.IGNORECASE):
                    evidence.append(f"status_reason:{expected_status}:{reason_pattern}")

        return evidence

    def _select_primary(self, detected_evidence: Dict[str, List[str]]) -> Optional[str]:
        if not detected_evidence:
            return None
        return max(
            detected_evidence.keys(),
            key=lambda vendor: (
                DETECTION_PRIORITY.get(vendor, 0),
                len(detected_evidence[vendor]),
            ),
        )

    def _filter_noise(
        self,
        detected_evidence: Dict[str, List[str]],
        primary_service: Optional[str],
    ) -> Set[str]:
        if not detected_evidence:
            return set()

        if not primary_service:
            return set(detected_evidence.keys())

        primary_priority = DETECTION_PRIORITY.get(primary_service, 0)
        if primary_priority < 75:
            return set(detected_evidence.keys())

        filtered: Set[str] = set()
        for vendor, vendor_evidence in detected_evidence.items():
            priority = DETECTION_PRIORITY.get(vendor, 0)
            if vendor == primary_service:
                filtered.add(vendor)
            elif priority >= 65 or len(vendor_evidence) >= 2:
                filtered.add(vendor)
            elif priority >= 50:
                filtered.add(vendor)
        return filtered

    def _match_header(
        self,
        headers: Dict[str, List[str]],
        header_name: str,
        pattern: str,
    ) -> Optional[str]:
        values = self._get_header_values(headers, header_name)
        if not values:
            return None
        compiled = re.compile(pattern, re.IGNORECASE)
        for value in values:
            if compiled.search(value):
                return value[:120]
        return None

    def _get_header_values(self, headers: Dict[str, List[str]], header_name: str) -> List[str]:
        target = header_name.lower()
        for key, values in headers.items():
            if key.lower() == target:
                return [v for v in values if v]
        return []

    def _get_header_value(self, headers: Dict[str, List[str]], header_name: str) -> Optional[str]:
        values = self._get_header_values(headers, header_name)
        return values[0] if values else None

    def _extract_cookie_names(self, headers: Dict[str, List[str]]) -> List[str]:
        names: List[str] = []
        for key, values in headers.items():
            if key.lower() != "set-cookie":
                continue
            for value in values:
                cookie_name = value.split("=", 1)[0].strip()
                if cookie_name:
                    names.append(cookie_name)
        return names

    def _build_content_blob(
        self,
        body: Optional[str],
        title: Optional[str],
    ) -> str:
        parts = []
        if title:
            parts.append(title)
        if body:
            parts.append(body)
        return "\n".join(parts)

    def _flatten_headers(self, headers: Dict[str, List[str]]) -> str:
        flattened_lines = []
        for key, values in headers.items():
            for value in values:
                flattened_lines.append(f"{key.lower()}: {value.lower()}")
        return "\n".join(flattened_lines)

    def analyze_protection_level(self, detection_result: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze level of protection based on detected services."""
        services = detection_result.get("services", [])

        enterprise_wafs = {
            "imperva-incapsula",
            "f5-big-ip",
            "citrix-netscaler",
            "barracuda",
            "fortinet",
            "checkpoint",
            "modsecurity",
        }
        cloud_wafs = {"cloudflare", "aws-elb", "azure-front-door", "sucuri"}
        cdns = {"akamai", "fastly", "cloudfront", "google"}

        protection_level = "none"
        categories = []

        if any(service in enterprise_wafs for service in services):
            protection_level = "enterprise"
            categories.append("enterprise-waf")

        if any(service in cloud_wafs for service in services):
            if protection_level == "none":
                protection_level = "cloud"
            categories.append("cloud-waf")

        if any(service in cdns for service in services):
            if protection_level == "none":
                protection_level = "basic"
            categories.append("cdn")

        return {
            "level": protection_level,
            "categories": categories,
            "service_count": len(services),
            "recommendations": self._get_recommendations(protection_level, services),
        }

    def _get_recommendations(self, protection_level: str, services: List[str]) -> List[str]:
        """Get security recommendations based on detected protection."""
        recommendations = []

        if protection_level == "none":
            recommendations.extend([
                "Consider implementing a Web Application Firewall (WAF)",
                "Evaluate CDN services for DDoS protection and performance",
                "Review origin server exposure and access controls",
            ])
        elif protection_level == "basic":
            recommendations.extend([
                "Consider upgrading to a dedicated WAF solution",
                "Review CDN security configurations and rules",
                "Ensure origin servers are not directly accessible",
            ])
        elif protection_level == "cloud":
            recommendations.extend([
                "Review cloud WAF rule configurations",
                "Enable additional security features if available",
                "Monitor WAF logs for attack patterns",
            ])
        elif protection_level == "enterprise":
            recommendations.extend([
                "Regularly review and update WAF rules",
                "Monitor security logs and alerting",
                "Conduct periodic security assessments",
            ])

        return recommendations